---
- hosts: all
  become: yes
  tasks:
    - name: Install Apache
      yum: 
        name: httpd
        state: latest
    - name: git checkout the website
      git:
        name: 
        state: started
