---
- hosts: localhost
  become: yes
  tasks:
    - name: Install Apache
      apt: 
        name: apache2
        state: latest
    - name: git checkout the website
      git:
        dest: /var/www/html
        repo: https://github.com/linuxacademy/content-introduction-to-ansible.git
