---
- hosts: localhost
  become: yes
  tasks:
    - name: Install Apache
      apt: 
        name: apache2
        state: latest
    - name: remove old web page
      command: "rm /var/www/html -r" 
    - name: git checkout the website
      git:
        dest: /var/www/html
        repo: https://github.com/linuxacademy/content-introduction-to-ansible.git
    - name: Start the Apache service
      service:
        name: apache2
        state: started
    
